version: '3.8'

services:
  middleware-datasources:
    container_name: middlewaredatasources
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8383:8080"
    restart: unless-stopped
    environment:
      # Puerto interno donde escucha Node
      PORT: ${PORT:-8080}

      # Otros 
      EUSER: ${EUSER}
      EPASS: ${EPASS}
      EHOST: ${EHOST}
      EPORT: ${EPORT}
      SEED: ${SEED}
      TIME_TOKEN: ${TIME_TOKEN}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      ZACATUCHE_HOST: ${ZACATUCHE_HOST}
      MANATI_HOST: ${MANATI_HOST}
      SPECIES_HOST: ${SPECIES_HOST}

      # Redis (clave)
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}

    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_middlewaredatasources
    restart: unless-stopped

