[repository]
ignore = [
    "node_modules",
    "dist",
    "build",
    ".git",
    "__pycache__",
    ".venv",
    "env"
]

[settings]
tree_max_depth = 1
model = "gpt-4o"
api = "openai"
temperature = 0.2
